### PR TITLE
feat: add copy code block feature

### LINKED ISSUE #69: Add a copy button to the code block
### Clear and concise description of the problem

Add a copy button to the top right corner of the code block

### Suggested solution

#  Add a copy button to the code block
When used on the official website, the code block has a copy button, hoping to add this function

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by yzh990918**
Kapture 2023-03-05 at 21 05 41

### Description
Add copy code block feature, close #69 .

### CODE REVIEW

**Comment by yzh990918** [comment]
@ddiu8081 You can redeploy to see the effect 😄 .

**Comment by h7ml** [comment]
> Kapture 2023-03-05 at 21 05 41 [ Kapture 2023-03-05 at 21 05 41 ](https://user-images.githubusercontent.com/46418596/222962214-783bfc48-8f2a-4d98-8a29-d8079fe2c845.gif) [ ](https://user-images.githubusercontent.com/46418596/222962214-783bfc48-8f2a-4d98-8a29-d8079fe2c845.gif)
> 
> ### Description
> Add copy code block feature, close #69 .
> 
> ### Linked Issues
> ### Additional context

Actually, I feel like the copy function could be added to the entire answer that is being copied.

**Comment by yzh990918** [comment]
> > Kapture 2023-03-05 at 21 05 41
> >       
> >         [
> >           
> >             Kapture 2023-03-05 at 21 05 41
> >           
> >         ](https://user-images.githubusercontent.com/46418596/222962214-783bfc48-8f2a-4d98-8a29-d8079fe2c845.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/46418596/222962214-783bfc48-8f2a-4d98-8a29-d8079fe2c845.gif)
> >         
> >        [ Kapture 2023-03-05 at 21 05 41 ](https://user-images.githubusercontent.com/46418596/222962214-783bfc48-8f2a-4d98-8a29-d8079fe2c845.gif)
> >       
> >         [
> >           
> >             Kapture 2023-03-05 at 21 05 41
> >           
> >         ](https://user-images.githubusercontent.com/46418596/222962214-783bfc48-8f2a-4d98-8a29-d8079fe2c845.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/46418596/222962214-783bfc48-8f2a-4d98-8a29-d8079fe2c845.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/46418596/222962214-783bfc48-8f2a-4d98-8a29-d8079fe2c845.gif)
> > ### Description
> > Add copy code block feature, close #69 .
> > ### Linked Issues
> > ### Additional context
> 
> Actually, I feel like the copy function could be added to the entire answer that is being copied.

I feel that the general scene of copying is to copy the code.

**Comment by yzh990918** [comment]
> > Kapture 2023-03-05 at 21 05 41 [ Kapture 2023-03-05 at 21 05 41 ](https://user-images.githubusercontent.com/46418596/222962214-783bfc48-8f2a-4d98-8a29-d8079fe2c845.gif) [ ](https://user-images.githubusercontent.com/46418596/222962214-783bfc48-8f2a-4d98-8a29-d8079fe2c845.gif)
> 
> > 
> 
> > ### Description
> 
> > Add copy code block feature, close #69 .
> 
> > 
> 
> > ### Linked Issues
> 
> > ### Additional context
> 
> 
> 
> Actually, I feel like the copy function could be added to the entire answer that is being copied.
> 
> 
> 
> 

I feel that the general scene of copying is to copy the code.

**Comment by ddiu8081** [comment]
Thanks for your contribution! I'm a little busy on Sunday, I'll check it out and merge it in later, please wait a bit!

**Comment by curly210102** [comment]
@yzh990918 好像没法复制普通文本了

**Comment by yzh990918** [comment]
> @yzh990918 好像没法复制普通文本了
> 
> 
> 
> 
> 
> 

稍等，我修复一下

**Pull request merged**
