### PR TITLE
feat: add forced assistant

### PR DESCRIPTION
**Pull request by QuietRocket**
unicorn

### Description

This PR permits you to force the output of the assistant for some given inputs. Since providing message examples is more powerful than the system prompt, this feature is indispensable.

By clicking on the crossed out robot button, you enter "forced assistant" mode. In that mode, inputs become user/assistant pairs. You can enter any number of examples, then press the button again to query the model as usual.

In the screenshot above, I provided the first two assistant answers. In messages that follow, it does its best to follow along.

This feature is inspired by the ChatGPT playground.

### Linked Issues

I wasn't able to find any (at least in English).

### Additional context

The robot icon comes from [the same source](https://icon-sets.iconify.design/mdi/robot-off-outline/) the clear icon came from.

### CODE REVIEW

**Comment by ddiu8081** [comment]
Hi QuickRocket, thanks for your advice and contribution!

I like this feature and I think it would be useful for debugging. However, I don't think the flow of the operation is easy enough to understand. It took me a while to understand how to provide message examples.

I prefer the flow of OpenAI's playground. The button to add a conversation is placed together with the chat message. I can think more naturally about adding a conversation here.

ScreenShot 2023-03-08 at 23 10 08@2x

In combination, I sketched what I had in mind:

ScreenShot 2023-03-08 at 23 21 21@2x

As you can see, first I would like to have the input box fixed at the bottom. If you don't mind, I will take up this PR after I make this UI change. 

Hope you understand and thanks for your support and contribution!

**Comment by fangyuan99** [comment]
> Hi QuickRocket, thanks for your advice and contribution!
> 
> I like this feature and I think it would be useful for debugging. However, I don't think the flow of the operation is easy enough to understand. It took me a while to understand how to provide message examples.
> 
> I prefer the flow of OpenAI's playground. The button to add a conversation is placed together with the chat message. I can think more naturally about adding a conversation here.
> 
> ScreenShot 2023-03-08 at 23 10 08@2x
> 
> In combination, I sketched what I had in mind:
> 
> ScreenShot 2023-03-08 at 23 21 21@2x
> 
> As you can see, first I would like to have the input box fixed at the bottom. If you don't mind, I will take up this PR after I make this UI change.
> 
> Hope you understand and thanks again for your support and contribution!

I want to know what software is used to draw the ui diagram of this example

**Comment by ddiu8081** [comment]
> I want to know what software is used to draw the ui diagram of this example

tldraw.

**Comment by QuietRocket** [comment]
Hi Diu, thank you for considering this PR.

I'm pretty sure OpenAI's ChatGPT playground UI changed overnight. I came up with a custom flow of interaction because I wasn't satisfied with yesterday's version. I agree that the new one you posted above is very pleasant and more intuitive (save the fact that it might not be entirely evident you can toggle between user and assistant by clicking on the bubble).

I look forward to the UI redesign so that we can add this feature afterwards 😉

**Pull request closed without merging**
