### PR TITLE
Fix: the problem that the li shows 2 incomplete numbers #103

### PR DESCRIPTION
**Pull request by whatqiu**
### Description
Fix the problem that the li shows 2 incomplete numbers
修复列表显示2位数不全的为题

### Linked Issues
#148 

### Additional context
Maybe DIu missed the merge(〃'▽'〃)

### CODE REVIEW

**Comment by yzh990918** [comment]
Please remove the extra code and resubmit the PR, Thanks.

**Comment by Hime-Hina** [comment]
image

Maybe using `list-style-position: inside;` is a better choice. Then setting left padding to a smaller value may have a good-looking.

**Comment by yzh990918** [comment]
> image
> 
> Maybe using `list-style-position: inside;` is a better choice. Then setting left padding to a smaller value may have a good-looking.

Maybe using `list-style-position: inside` , this adjustment is correct.

**Comment by Hime-Hina** [comment]
> `list-style-position: inside` will cause overflow, as the marker occupied space for paragraph. That's why use 2em padding, #148

I noticed that situation, but it's better than the list item number partially displayed.

image

And using 2em padding doesn't solve the problem perfectly. I found another way to solve it: delete the `overflow-hidden` class from the parent element of the `ol`. But I'm not exactly sure what this class does. It seems that the ChatGPT official website does not have such a situation, and it does not use styles like `overflow: hidden`.

image

**Comment by curly210102** [comment]
@Hime-Hina Be careful of overflow caused by long lines of code. 
https://github.com/ddiu8081/chatgpt-demo/commit/89a8a2732caf13bec37ac17673c1206a23d188ed the overflow-hidden seems used to limit the code block.

SCR-20230316-pw0

The message block needs to inherit the remaining space of the flex container, ChatGPT WebUI has set a fixed width to achieve this.
image

**Pull request closed without merging**
