### PR TITLE
add proxy

### PR DESCRIPTION
**Pull request by quzard**
由于openai的api在国内被墙，添加代理配置
根据env里是否配置代理来判断fetch请求是否添加代理

### CODE REVIEW

**Comment by DerekTso** [comment]
我今天在本地电脑部署完试了一下，出错了 fetch failed
```
{
  "name": "ConnectTimeoutError",
  "code": "UND_ERR_CONNECT_TIMEOUT",
  "message": "Connect Timeout Error"
}
```
应该是代理的问题，如何解决这个问题呢

**Comment by ddiu8081** [comment]
You have added new dependencies, please submit the `package.json` file along with it, thanks!

**Comment by quzard** [comment]
> You have added new dependencies, please submit the `package.json` file along with it, thanks!

It doesn't need any additional dependencies added to package.json

**Comment by quzard** [comment]
> You have added new dependencies, please submit the `package.json` file along with it, thanks!

I have added the dependency node-fetch to package.json.

**Comment by ddiu8081** [comment]
Vercel 的 Edge Runtime 仅支持 `fetch` API，不能使用 `node-fetch` 等三方依赖，因此这样无法部署上去。我先去搞一下这个问题

**Comment by skywoodlin** [comment]
> 
哥们， 你的docker镜像无法跑起来， 即便我用的是你刚才又上传了一个新版本。 你的仓库里没有issue, 我只能在这里跟你说了
docker version: 20.10.7
docker-compose version: 2.16.0
报错： Options:[rbind]}: mount destination env not absolute: unknown

**Pull request merged**
